package com.neobank.audit;
public enum AuditAction {
    LOGIN, LOGOUT, REGISTER, PASSWORD_CHANGE, PASSWORD_RESET, MFA_ENABLE, MFA_DISABLE,
    PROFILE_UPDATE, ACCOUNT_CREATE, TRANSFER, CARD_CREATE, CARD_BLOCK, LOAN_APPLY, KYC_SUBMIT,
    ADMIN_ACTION, FRAUD_INVESTIGATION
}
