spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neobank_db
    username: neobank_user
    password: neobank_secure_password_2026
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.neobank: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
