spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/neobank_db}
    username: ${SPRING_DATASOURCE_USERNAME:neobank_user}
    password: ${SPRING_DATASOURCE_PASSWORD:neobank_secure_password_2026}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.neobank: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
